### ISSUE TITLE
Totem Swapping

### ISSUE THREAD

**Issue by Maroej** [MOUZU/TotemTimers-Enhanced#5]
With the latest development on Elysium https://forum.elysium-project.org/topic/34789-development-update-25012017/
Totem swaping is now viable. 
Would love it if you could set the wf timer to tick from 10-0 (duration of WF) even when you swap to Agility totem like in the TBC version. 

Beg you Lyq :D

**Comment by MOUZU** [comment]
Is this still relevant on Light's Hope?

**Comment by MOUZU** [comment]
If I understand the requirement correct: when you've casted WF Totem and switch to another totem it should continue the ongoing WF Timer until the WF Buff runs out.
That would mean I have to change the way the tick works for the Windfury totem. Previously in this AddOn the tick displayed when the Totem applies the next round of Windfury on all group members. I would have to change this to display the uptime of the buff and as well make an exception so that the timer does not disappear when switching to other Air totems.

I will look into making the requested adjustments. Thanks for your input!

**Comment by MOUZU** [comment]
This feature is included in the latest update. It is compatible with and without OmniCC.
